base_model: Qwen/Qwen2-1.5B
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: _escavai_datasets/openie_256.jsonl
    type: sharegpt
    chat_template: chatml
   
chat_template: chatml

dataset_prepared_path:
val_set_size: 0.01
output_dir: ./outputs/out

sequence_len: 256
sample_packing: true
pad_to_sequence_len: true

wandb_project: escavai
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 12
micro_batch_size: 6
num_epochs: 3
lr_scheduler: cosine
learning_rate: 5e-5

train_on_inputs: false
group_by_length: false

bf16: true
fp16:
tf32: true
optimizer: paged_adamw_8bit
unsloth_cross_entropy_loss: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
  
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 1
eval_table_size:
saves_per_epoch: 0
save_total_limit: 1
debug:
deepspeed:
weight_decay: 0.0
special_tokens:
  eos_token: "<|im_end|>"
